# Generated by Django 3.1.4 on 2021-01-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0004_auto_20210111_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='average_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Минимальная цена за 6 месяцев'),
        ),
        migrations.AddField(
            model_name='product',
            name='current_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Текущая цена'),
        ),
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Старая цена'),
        ),
    ]
