# Generated by Django 3.1.4 on 2021-01-11 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0005_auto_20210111_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_name',
        ),
    ]
