# Generated by Django 3.1.4 on 2021-01-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0006_remove_product_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='average_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Минимальная цена за 6 месяцев'),
        ),
        migrations.AlterField(
            model_name='product',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Текущая цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Старая цена'),
        ),
    ]
