# Generated by Django 3.1.5 on 2021-01-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0011_auto_20210121_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatormessage',
            name='operator_url',
            field=models.CharField(default='-', max_length=255, verbose_name='Сайт с товаром'),
        ),
    ]
