# Generated by Django 3.1.5 on 2021-01-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0012_operatormessage_operator_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='activemonitoring',
            name='waiting_price',
            field=models.PositiveIntegerField(default=0, help_text='Если указан 0, значит пользователь не указал желаемую цену', verbose_name='Ожидаемая цена пользователя'),
        ),
    ]
