# Generated by Django 3.1.5 on 2021-01-22 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0013_activemonitoring_waiting_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operatormessage',
            options={'verbose_name': 'Сообщение рассылка', 'verbose_name_plural': 'Сообщения рассылка'},
        ),
        migrations.CreateModel(
            name='OperatorMessageWaiting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_price', models.PositiveIntegerField(default=0, verbose_name='Цена оператора')),
                ('operator_url', models.CharField(default='-', max_length=255, verbose_name='Сайт с товаром')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ugc.product', verbose_name='ID товара')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ugc.profile', verbose_name='ID пользователя')),
            ],
            options={
                'verbose_name': 'Сообщение ожидание',
                'verbose_name_plural': 'Сообщения ожидания',
            },
        ),
    ]
