# Generated by Django 3.1.7 on 2021-02-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0014_auto_20210122_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='activemonitoring',
            name='test',
            field=models.CharField(default='1', max_length=255),
        ),
    ]
