# Generated by Django 3.1.7 on 2021-02-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0015_activemonitoring_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activemonitoring',
            name='test',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
