# Generated by Django 3.1.7 on 2021-02-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0016_auto_20210226_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activemonitoring',
            name='test',
            field=models.CharField(default='1', max_length=255),
        ),
    ]
