# Generated by Django 3.1.7 on 2021-02-26 12:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0017_auto_20210226_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activemonitoring',
            name='test',
        ),
        migrations.AddField(
            model_name='activemonitoring',
            name='time_published',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время добавления'),
            preserve_default=False,
        ),
    ]
