# Generated by Django 3.1.7 on 2021-02-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0018_auto_20210226_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatormessage',
            name='operator_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена оператора'),
        ),
        migrations.AlterField(
            model_name='operatormessagewaiting',
            name='operator_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена оператора'),
        ),
    ]
