# Generated by Django 3.1.7 on 2021-02-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0019_auto_20210226_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='activemonitoring',
            name='id_monitoring',
            field=models.CharField(default=76423977, max_length=255, verbose_name='ID мониторинга'),
        ),
    ]
