# Generated by Django 3.1.7 on 2021-02-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0021_auto_20210227_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activemonitoring',
            name='id_monitoring',
            field=models.CharField(default='tr1aeyya', max_length=255, unique=True, verbose_name='ID мониторинга'),
        ),
    ]
