# Generated by Django 3.1.7 on 2021-02-27 14:58

from django.db import migrations, models
import ugc.models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0022_auto_20210227_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activemonitoring',
            name='id_monitoring',
            field=models.CharField(default=ugc.models.f, max_length=255, unique=True, verbose_name='ID мониторинга'),
        ),
    ]
