# Generated by Django 3.1.7 on 2021-02-27 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0023_auto_20210227_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operatormessage',
            name='product',
        ),
        migrations.RemoveField(
            model_name='operatormessage',
            name='profile',
        ),
        migrations.AddField(
            model_name='operatormessage',
            name='monitoring',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='ugc.activemonitoring', verbose_name='ID мониторинга'),
            preserve_default=False,
        ),
    ]
