# Generated by Django 3.1.7 on 2021-04-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0027_auto_20210227_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='operator_message',
            field=models.TextField(default='', max_length=255, verbose_name='Сообщение от оператора'),
        ),
        migrations.AddField(
            model_name='product',
            name='operator_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена предоставленная оператором'),
        ),
    ]
