# Generated by Django 3.1.7 on 2021-04-29 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0030_product_cashback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operatormessage',
            name='monitoring',
        ),
        migrations.RemoveField(
            model_name='operatormessagewaiting',
            name='monitoring',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='OperatorMessage',
        ),
        migrations.DeleteModel(
            name='OperatorMessageWaiting',
        ),
    ]
