# Generated by Django 3.1.7 on 2021-05-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0032_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activemonitoring',
            name='time_published',
            field=models.DateTimeField(verbose_name='Время добавления'),
        ),
    ]
